ASPMVC/ASPMVC/ASPMVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ASPMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Mariu()
        {
            ViewBag.Message = "Your mariu page.";

            return View();
        }
    }
}

ASPMVC/ASPMVC/ASPMVC/Controllers/MyController.cs
using System.Web.Mvc;

namespace ASPMVC.Controllers
{
    public class MyController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Pseudo(string name)
        {
            ViewBag.name = name;
            return View();
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult FormAns(string firstname, string lastname)
        {
            ViewBag.firstname = firstname;
            ViewBag.lastname = lastname;
            return View();
        }
    }
}

ASPMVC/ASPMVC/ASPMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ASPMVC/ASPMVC/ASPMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

ASPMVC/ASPMVC/ASPMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ASPMVC/ASPMVC/ASPMVC/Views/Home/Mariu.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Mariu le grand</title>
</head>
<body>
<div>
      <h1>Bienvenue Mariu !</h1>
</div>
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/My/Form.cshtml
@model dynamic

<!DOCTYPE html>

<html>
<head>
    <title>Le form</title>
</head>
<body>
<div>
        <form method="post" action="@Url.Action("FormAns","My")">
            First name:<br>
            <input type="text" name="firstname" value="Mickey"><br>
            Last name:<br>
            <input type="text" name="lastname" value="Mouse"><br><br>
            <input type="submit" value="Submit">
        </form>
</div>
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/My/FormAns.cshtml
@model dynamic

<!DOCTYPE html>

<html>
<head>
    <title>Réponse du form</title>
</head>
<body>
<div>
    <h1>Bonjour mon cher @ViewBag.firstname</h1>
</div>
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/My/Index.cshtml
@model dynamic

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    
</div>
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/My/Pseudo.cshtml
@model dynamic

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <h1>Bonjour @ViewBag.name</h1>
</div>
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Mariu", "Mariu", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2018 - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASPMVC/ASPMVC/ASPMVC/Views/bd/Index.cshtml
@using System.Data.Linq.Mapping
@using Microsoft.Ajax.Utilities
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
    var db =
}

<h2>title</h2>
@foreach(var row in db.Query)